Add Docker File and Docker compose.
mpcabete/bombcrypto-bot pull request #190
Opened 2021-12-08 23:13 UTC by jeanvetorello

add Docker File and docker-compose 

Pessoal estou adicionando um docker file e um docker compose para ajudar o pessoal a utilizar varias contas, ao inves de utilizar maquinas virtuais, e tambem para  facilitar o uso em vps.

para rodar bastar ter docker e docker compose instalado e ajustar o - VNC_PASSWORD=COLOCARUMASENHAAQUI.  depois docker-compose up -d --build
essa image já tem o vnc instalado entao depois que ela rodar  entre com o vnc no 127.0.0.1:5900 , coloca a senha que está la na variavel e pronto. vc está acessando remoto um linux,

apos isso abre o firefox instale metamask , add a rede da bsc e pronto.
vai ter uma pasta com o repositorio atualizado no /root/Desktop

OBS: essa ultima atualizaçao do requirements.txt quebrou o build do container entao retirar o simpleaudio pois não tem audio mesmo .

TODO: acrescentar um volume onde guarde as info do firefox para que não se perca quando o continaer reinicar.

2021-12-09 02:54 UTC, fguide commented
Boa ideia, seria interessante adicionar na imagem também o node.js para ser possível configurar o NoVNC e fazer o acesso remoto mais simples por HTML5

Um exemplo:
https://github.com/theasp/docker-novnc

2021-12-09 11:09 UTC, itxtoledo requested changes
Por favor retire as alterações que não tem a ver com o docker, isso deve ser evitado pois deixa o git blame bagunçado, e não desative features que são necessárias.

2021-12-09 11:09 UTC, itxtoledo commented on index.py
> +    return response.json()
Isso não tem a ver com a alteração principal.

2021-12-09 11:09 UTC, itxtoledo commented on index.py
> +    tele = telegram_bot_sendtext("⚠️ ATENÇÃO! \n\n 🧩 RESOLVER NOVO CAPTCHA!")
Você alterou outras partes do código que não tem a ver com a adição do docker.

2021-12-09 11:17 UTC, jeanvetorello commented on index.py
> +    return response.json()
apa desculpe tinha feito essas alteração  so pra min, oque vale so so o docker file e o docker compose comites depois vou remover

2021-12-09 11:54 UTC, jeanvetorello commented
> Boa ideia, seria interessante adicionar na imagem também o NoVNC e fazer o acesso remoto mais simples por HTML5
> 
> Um exemplo: https://github.com/theasp/docker-novnc

feito no ultimo commit

2021-12-09 12:03 UTC, closed without merging

2022-01-11 23:48 UTC, lucasvieceli commented
isso ja n deveria estar no branch main ??

estou procurando e não encontro