enviar screenshot do stash periodicamente via discord webhook
mpcabete/bombcrypto-bot pull request #562
Opened 2022-01-05 03:42 UTC by crvvdev

Só pra constar que eu não sei nada de Python, sou programador C/C++ mas sabia que seria fácil implementar isso.

Eu não fui tão fundo a ponto de gerar logs ou de criar uma logica pra só tirar uma screenshot e enviar quando todos os heróis cansarem, ele simplesmente tira uma screenshot assim que o script é acionado para entrar no treasure hunt.

Acho que tem um potencial enorme caso isso seja bem implementado, por exemplo obter o link do webhook via a config.yaml, adicionar timers, checagens mais extensas, etc.. 

Enfim, pra quem precisa de algo parecido isso já quebra um galho enorme pra mim, posso checar o quanto lucrei remotamente a qualquer instante só abrindo meu Discord, espero que sirva de ajuda.

2022-01-06 15:26 UTC, kclazu commented
Fala meu camarada, 

Inclui suas alterações nos meus arquivos, porém, nao ficou claro pra mim em qual momento ele abre a stash, tira o screenshot e envia pro discord. Quando essa acao deveria ocorrer e como chega no discord? Como se fosse um novo chat de um user bot?

Obrigado e abracos!

2022-01-06 22:21 UTC, crvvdev commented
> Fala meu camarada,
> 
> Inclui suas alterações nos meus arquivos, porém, nao ficou claro pra mim em qual momento ele abre a stash, tira o screenshot e envia pro discord. Quando essa acao deveria ocorrer e como chega no discord? Como se fosse um novo chat de um user bot?
> 
> Obrigado e abracos!

Basicamente eu criei um servidor e no canal principal eu criei uma Webhook e só copiei o link e pronto, o bot envia a imagem no canal sem problemas.

E sobre a ação eu deixei pra ela ocorrer assim que o bot clica no icone do treasure hunt, ou seja, assim que ele entra no mapa ele já clica no baú e tira print e envia e fecha a janela do baú e continua a execução do bot normalmente

2022-01-06 22:32 UTC, kclazu commented
Criei um servidor, como faço pra ele enviar a screen para este servidor?

Mais uma questão. Apesar de ter inserido seu código em meu arquivo conforme suas alterações, ele nao esta clicando na stash e tirando o print. Alguma ideia?

2022-01-06 23:18 UTC, LuisShmu commented
@crvvdev Legal cara! 
Adicionei aqui no meu bot e ficou muito bom, adicionei para para ele ficar mandando a cada 50 min, estou pensando em quais partes posso adicionar para ele enviar para o discord.

2022-01-06 23:19 UTC, LuisShmu commented
> Legal! Mais uma questão. Apesar de ter inserido seu código em meu arquivo conforme suas alterações, após clicar na stash, algum crash ocorre e o bot fecha. Alguma ideia do que pode ser?
> 
> `def sendStashToDiscord():
> 
> ```
> if clickBtn(images['stash']):
>     time.sleep(2)
> 
>     q = datetime.datetime.now()
>     d = q.strftime("%d%m%Y%H%M")
>     image_file = os.path.join('screenshots', d +'.png')
>     pic = pyautogui.screenshot(image_file)
> 
>     time.sleep(1)
>     webhook = discord.Webhook.from_url('https://discord.com/api/webhooks/928778780967829544/YaUB6wJEzPQJf7V6eh3z3PoYFeJ7UkYYpOsf95K1OoRujMHojhJxE2eYbsUQaXb7sUeA', adapter=discord.RequestsWebhookAdapter())
>     webhook.send(file=discord.File(image_file))
> 
>     clickBtn(images['x'])`
> ```

Você criou a pasta 'screenshots'?

2022-01-06 23:22 UTC, kclazu commented
> Você criou a pasta 'screenshots'?

criei, sim. Ele crash assim que clica no bau..

Outra coisa que esta acontecendo é que ele as vezes clica no botao settings ao invés do bau.

2022-01-07 00:40 UTC, crvvdev commented
o PR ja contem a pasta screenshot justamente pra evitar que esse crash aconteça, mas sim, é necessário que a pasta exista :)

2022-01-07 02:50 UTC, kclazu commented
Talvez porque eu esteja usando 2 monitores? Estou usando estas alterações https://github.com/mpcabete/bombcrypto-bot/pull/30/files. Será que tem alguma interferência?

2022-01-12 17:44 UTC, iJuniorX commented
Pode me ajudar com esse erro @crvvdev , ele manda a primeira vez e depois cabo, morreu bot.
![image](https://user-images.githubusercontent.com/87344117/149193566-31df4a89-ef1c-4bd8-9844-6ca1f47e83c3.png)

2022-01-15 03:13 UTC, raphaaaodev commented
Para mim não fazia sentido ficar somando imagens na pasta screenshots... então coloquei para remover tudo da pasta após o envio

```
import glob

[...]
        webhook.send(file=discord.File(image_file))

       #Linhas adicionadas:
        time.sleep(2)
        filelist = glob.glob(os.path.join('screenshots','*'))
        for f in filelist:
            os.remove(f)
       #Fim das linhas adicionadas

        clickBtn(images['x'])

[...]
```

2022-01-29 19:04 UTC, gcxmtv commented
Para mandar no bot do telegram, é possível?

2022-01-31 15:49 UTC, brcake approved these changes

2022-01-31 16:48 UTC, raphaaaodev requested changes
alterar primeiro argumento da função

2022-01-31 16:48 UTC, raphaaaodev commented on index.py
> +        webhook = discord.Webhook.from_url('<webhook url>', adapter=discord.RequestsWebhookAdapter())
Alterar primeiro argumento da função por uma variável recebida do arquivo config.yaml

2022-01-31 17:32 UTC, gcxmtv commented on index.py
> +        webhook = discord.Webhook.from_url('<webhook url>', adapter=discord.RequestsWebhookAdapter())
Eu ainda estou estudando python.. nesse caso onde tá discord eu coloco telegram ? E onde insere o token e o id ?

2022-01-31 17:53 UTC, raphaaaodev commented on index.py
> +        webhook = discord.Webhook.from_url('<webhook url>', adapter=discord.RequestsWebhookAdapter())
> Eu ainda estou estudando python.. nesse caso onde tá discord eu coloco telegram ? E onde insere o token e o id ?

Amigo, essa implementação é para o aplicativo Discord. Dê uma pesquisada por telegram nos PRs, com o telegram a implementação é diferente, não tem como reaproveitar o código dessa PR.

E pela sua pergunta, você precisa dar uma focada melhor nos fundamentos da orientação a objeto... e sobre imports no python.

2022-01-31 18:08 UTC, gcxmtv commented on index.py
> +        webhook = discord.Webhook.from_url('<webhook url>', adapter=discord.RequestsWebhookAdapter())
Realmente a questão da orientação a objeto pra mim ainda não consegui compreender de forma completa. Eu fiz o de Java e tô reestudando tudo porque ainda tá um pouco confuso na minha cabeça .. 

Minha pergunta era essa mesmo, se teria como aproveitar o código.. mas vou estudar com mais calma.. ainda tô bem no início do curso de Python

2022-02-01 01:21 UTC, brcake commented on index.py
> +        webhook = discord.Webhook.from_url('<webhook url>', adapter=discord.RequestsWebhookAdapter())
@raphaaaodev  eu fiz todos os procedimentos, peguei esse código e implementei no meu código aqui, porém não acontece nada! fiz a webhook no meu canal do discord numa sala de texto.

não me volta nenhum erro!

2022-04-09 18:58 UTC, closed without merging